version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: moeasy_local_db
      MYSQL_USER: master
      MYSQL_PASSWORD: masterpw
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.12
    # platform: linux/arm64
    container_name: milvus-etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
      ETCD_SNAPSHOT_COUNT: "5000"
    command:
      - etcd
      - --data-dir=/etcd_data
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=default=http://0.0.0.0:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster
    volumes:
      - ./milvus/etcd:/etcd_data
    ports:
      - "2379:2379"
    restart: unless-stopped

  milvus-minio:
    image: minio/minio:RELEASE.2024-12-13T22-19-12Z
    # platform: linux/arm64
    container_name: milvus-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./milvus/minio:/data
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO 콘솔
    restart: unless-stopped

  milvus:
    image: milvusdb/milvus:v2.4.3
    # platform: linux/arm64
    container_name: milvus-standalone
    depends_on:
      - milvus-etcd
      - milvus-minio
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_USE_SSL: "false"
    command: [ "milvus", "run", "standalone" ]
    volumes:
      - ./milvus/data:/var/lib/milvus
    ports:
      - "19530:19530" # gRPC (pymilvus 연결)
      - "9091:9091"   # metrics
    restart: unless-stopped